#!/usr/bin/env bash
# Rebuild the codec bundle that used to be distributed as web_deps.tar.gz
# (now 404). Sources:
#   ogv.js 1.8.6 release zip (has SIMD builds, npm lacks them) -> ogvjs-1.8.6/
#   yuv-canvas@1.2.6 (npm)    -> yuv-canvas-1.2.6.js
#   opusscript@0.1.1 (npm)    -> libopus.js (audio decoder worker, generated)
#
# Usage: fetch-codecs.sh <flutter-web-dir>
set -euo pipefail

WEB_DIR="${1:?usage: fetch-codecs.sh <flutter-web-dir>}"
OGV_VERSION="1.8.6"
YUVCANVAS_VERSION="1.2.6"
OPUSSCRIPT_VERSION="0.1.1"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fetch_npm() { # <package> <version> <dest-dir>
  local name="$1" version="$2" dest="$3"
  mkdir -p "$dest"
  curl -sL "$(npm view "${name}@${version}" dist.tarball)" | tar xz -C "$dest"
}

# --- ogv.js (video decoders) -------------------------------------------------
# NOTE: the npm package lacks the SIMD decoder builds ("yarn add has no simd",
# see js/src/codec.js), so use the upstream release zip which has them all.
OGV_DIR="$WEB_DIR/ogvjs-${OGV_VERSION}"
if [ ! -f "$OGV_DIR/ogv.js" ]; then
  echo ">> fetching ogvjs-${OGV_VERSION} release zip"
  curl -sL "https://github.com/bvibber/ogv.js/releases/download/${OGV_VERSION}/ogvjs-${OGV_VERSION}.zip" \
    -o "$TMP/ogvjs.zip"
  (cd "$TMP" && unzip -qo ogvjs.zip)
  cp -r "$TMP/ogvjs-${OGV_VERSION}" "$WEB_DIR/"
fi

# --- yuv-canvas (YUV -> WebGL renderer) --------------------------------------
# The npm package's entry is CommonJS (require('./FrameSink.js') ...); the
# browser needs a self-contained bundle exposing the YUVCanvas global, so we
# bundle src/yuv-canvas.js with esbuild.
if [ ! -f "$WEB_DIR/yuv-canvas-${YUVCANVAS_VERSION}.js" ]; then
  echo ">> bundling yuv-canvas@${YUVCANVAS_VERSION}"
  fetch_npm yuv-canvas "$YUVCANVAS_VERSION" "$TMP/yuv"
  npx -y esbuild@0.20.2 "$TMP/yuv/package/src/yuv-canvas.js" \
    --bundle --format=iife --global-name=YUVCanvas \
    --outfile="$WEB_DIR/yuv-canvas-${YUVCANVAS_VERSION}.js"
fi

# --- libopus.js (audio decoder worker) ---------------------------------------
# The original libopus.js was a custom emscripten build shipped in
# web_deps.tar.gz. We regenerate an equivalent worker from opusscript.
# Protocol expected by flutter/web/js/src/globals.js:
#   in : {channels, sampleRate}  (init)
#   in : ArrayBuffer             (one opus packet, transferred)
#   out: Float32Array            (decoded PCM, transferred)
if [ ! -f "$WEB_DIR/libopus.js" ]; then
  echo ">> generating libopus.js from opusscript@${OPUSSCRIPT_VERSION}"
  fetch_npm opusscript "$OPUSSCRIPT_VERSION" "$TMP/opus"
  OPUS_SRC="$(find "$TMP/opus" -name 'index.js' -path '*opusscript*' | head -1)"
  [ -n "$OPUS_SRC" ] || OPUS_SRC="$(find "$TMP/opus" -name '*.js' | head -1)"
  {
    echo '// Generated by deploy/v1/src/fetch-codecs.sh - opus decoder worker.'
    echo '// opusscript (CJS/UMD) is inlined with a CommonJS shim, then wrapped'
    echo '// in the worker protocol expected by globals.js.'
    echo 'var module = { exports: {} }; var exports = module.exports;'
    cat "$OPUS_SRC"
    cat <<'EOF'

const OpusScript = module.exports;
let decoder = null;

self.onmessage = function (e) {
  const d = e.data;
  if (d && typeof d === "object" && !(d instanceof ArrayBuffer) && "channels" in d) {
    const app = OpusScript.Application ? OpusScript.Application.AUDIO : 2049;
    decoder = new OpusScript(d.sampleRate, d.channels, app);
    return;
  }
  if (!decoder) return;
  const pcm = decoder.decode(new Uint8Array(d)); // Int16Array
  const f32 = new Float32Array(pcm.length);
  for (let i = 0; i < pcm.length; i++) f32[i] = pcm[i] / 32768;
  self.postMessage(f32, [f32.buffer]);
};
EOF
  } > "$WEB_DIR/libopus.js"
fi

echo ">> codec bundle ready in $WEB_DIR"
